secrets:
  serverEnv:
    file: ./.env

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio-data:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_PASS}
    command: server --console-address :9001 /data
  website:
    restart: unless-stopped
    platform: linux/x86_64
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - PUBLIC_SERVER_HOST=http://localhost:5999
    network_mode: host
    secrets:
      - serverEnv
